spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://db:5432/erp_auth}
    username: ${POSTGRES_USER:erp_admin}
    password: ${POSTGRES_PASSWORD:admin1234}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

management:
  tracing:
    sampling:
      probability: 1.0

  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: http://otel-collector:4318

  otlp:
    metrics:
      export:
        enabled: false

auth:
  jwt:
    # minimo 32 bytes recomendado para HS256 en serio
    secret: "change-this-super-secret-key-very-long-32-bytes-min"
    access-token-expiration-minutes: 15
  refresh:
    expiration-days-default: 7
    expiration-days-remember-me: 30
    pepper: "change-me-pepper"
